"""monto_mensual

Revision ID: 11c0b5088831
Revises: 989b1be45903
Create Date: 2026-07-01 11:25:23.448402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11c0b5088831'
down_revision: Union[str, Sequence[str], None] = '989b1be45903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('montos_mensuales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profesor_id', sa.UUID(), nullable=True),
    sa.Column('nombre_layout', sa.String(length=200), nullable=False),
    sa.Column('regimen_fiscal', sa.String(length=3), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('iva_trasladado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('iva_retenido', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('isr_retenido', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['profesor_id'], ['profesores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_montos_mensuales_profesor_id'), 'montos_mensuales', ['profesor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_montos_mensuales_profesor_id'), table_name='montos_mensuales')
    op.drop_table('montos_mensuales')
    # ### end Alembic commands ###
