"""uuid_schema

Revision ID: 394c0778d3ec
Revises: 
Create Date: 2026-06-09 16:33:58.545568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '394c0778d3ec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogo_claves',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clave', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogo_claves_clave'), 'catalogo_claves', ['clave'], unique=True)
    op.create_table('facturas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('uuid_cfdi', sa.String(length=36), nullable=False),
    sa.Column('rfc_emisor', sa.String(length=13), nullable=False),
    sa.Column('nombre_emisor', sa.String(length=200), nullable=True),
    sa.Column('regimen_emisor', sa.String(length=3), nullable=True),
    sa.Column('fecha_emision', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_timbrado', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('iva_trasladado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('iva_retenido', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('isr_retenido', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('clave_servicio', sa.String(length=20), nullable=True),
    sa.Column('clave_unidad', sa.String(length=20), nullable=True),
    sa.Column('descripcion_concepto', sa.Text(), nullable=True),
    sa.Column('forma_pago', sa.String(length=3), nullable=True),
    sa.Column('metodo_pago', sa.String(length=3), nullable=True),
    sa.Column('uso_cfdi', sa.String(length=5), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('motivo_rechazo', sa.Text(), nullable=True),
    sa.Column('fecha_validacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facturas_rfc_emisor'), 'facturas', ['rfc_emisor'], unique=False)
    op.create_index(op.f('ix_facturas_uuid_cfdi'), 'facturas', ['uuid_cfdi'], unique=True)
    op.create_table('profesores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rfc', sa.String(length=13), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('correo', sa.String(length=200), nullable=False),
    sa.Column('regimen_fiscal', sa.String(length=3), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profesores_rfc'), 'profesores', ['rfc'], unique=True)
    op.create_table('profesor_claves',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profesor_id', sa.UUID(), nullable=False),
    sa.Column('catalogo_clave_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['catalogo_clave_id'], ['catalogo_claves.id'], ),
    sa.ForeignKeyConstraint(['profesor_id'], ['profesores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('validacion_detalle',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('factura_id', sa.UUID(), nullable=False),
    sa.Column('campo', sa.String(length=100), nullable=False),
    sa.Column('valor_recibido', sa.String(length=500), nullable=True),
    sa.Column('valor_esperado', sa.String(length=500), nullable=True),
    sa.Column('resultado', sa.Boolean(), nullable=False),
    sa.Column('mensaje', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validacion_detalle')
    op.drop_table('profesor_claves')
    op.drop_index(op.f('ix_profesores_rfc'), table_name='profesores')
    op.drop_table('profesores')
    op.drop_index(op.f('ix_facturas_uuid_cfdi'), table_name='facturas')
    op.drop_index(op.f('ix_facturas_rfc_emisor'), table_name='facturas')
    op.drop_table('facturas')
    op.drop_index(op.f('ix_catalogo_claves_clave'), table_name='catalogo_claves')
    op.drop_table('catalogo_claves')
    # ### end Alembic commands ###
