"""factura: receptor, moneda, origen, pdf_cotejo

Revision ID: 6783f5721a24
Revises: 9f4da7b5aa8b
Create Date: 2026-07-16 13:53:33.682171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6783f5721a24'
down_revision: Union[str, Sequence[str], None] = '9f4da7b5aa8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facturas', sa.Column('rfc_receptor', sa.String(length=13), nullable=True))
    op.add_column('facturas', sa.Column('nombre_receptor', sa.String(length=200), nullable=True))
    op.add_column('facturas', sa.Column('moneda', sa.String(length=3), nullable=True))
    op.add_column('facturas', sa.Column('origen', sa.String(length=20), nullable=False, server_default='xml'))
    op.add_column('facturas', sa.Column('pdf_cotejo', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facturas', 'pdf_cotejo')
    op.drop_column('facturas', 'origen')
    op.drop_column('facturas', 'moneda')
    op.drop_column('facturas', 'nombre_receptor')
    op.drop_column('facturas', 'rfc_receptor')
    # ### end Alembic commands ###
