"""rfc_emisor en montos_mensuales

Revision ID: 9f4da7b5aa8b
Revises: 11c0b5088831
Create Date: 2026-07-16 13:08:03.273480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f4da7b5aa8b'
down_revision: Union[str, Sequence[str], None] = '11c0b5088831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('montos_mensuales', sa.Column('rfc_emisor', sa.String(length=13), nullable=True))
    op.create_index(op.f('ix_montos_mensuales_rfc_emisor'), 'montos_mensuales', ['rfc_emisor'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_montos_mensuales_rfc_emisor'), table_name='montos_mensuales')
    op.drop_column('montos_mensuales', 'rfc_emisor')
    # ### end Alembic commands ###
