"""confirmacion correo profesor

Revision ID: d50f5838fbe4
Revises: d6670ced9ceb
Create Date: 2026-07-18 12:01:45.885125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd50f5838fbe4'
down_revision: Union[str, Sequence[str], None] = 'd6670ced9ceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuracion_correo', sa.Column('confirmaciones_activas', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('facturas', sa.Column('confirmacion_enviada', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facturas', 'confirmacion_enviada')
    op.drop_column('configuracion_correo', 'confirmaciones_activas')
    # ### end Alembic commands ###
