"""configuracion_correo

Revision ID: d6670ced9ceb
Revises: 6783f5721a24
Create Date: 2026-07-17 19:39:20.904504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6670ced9ceb'
down_revision: Union[str, Sequence[str], None] = '6783f5721a24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion_correo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('imap_host', sa.String(length=200), nullable=False),
    sa.Column('imap_port', sa.Integer(), nullable=False),
    sa.Column('imap_user', sa.String(length=200), nullable=False),
    sa.Column('imap_folder', sa.String(length=100), nullable=False),
    sa.Column('poll_minutos', sa.Integer(), nullable=False),
    sa.Column('remitentes_permitidos', sa.Text(), nullable=True),
    sa.Column('auto_activo', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuracion_correo')
    # ### end Alembic commands ###
